// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CpuUsage() {
  return window['go']['api']['GreetingApi']['CpuUsage']();
}

export function SayHello(arg1) {
  return window['go']['api']['GreetingApi']['SayHello'](arg1);
}
